# Use a imagem oficial do PHP com Apache
FROM php:8.2-apache

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configurar o diretório de trabalho
WORKDIR /var/www

# Copiar arquivos do projeto
# COPY . .

# Instalar dependências do Laravel
# RUN composer install --no-dev --optimize-autoloader

# Definir permissões para o Laravel
# RUN chown -R www-data:www-data storage bootstrap/cache

# Expor a porta do Apache
EXPOSE 8000

# Iniciar o Laravel com Apache
# CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]