version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - command-service
      - query-service
    networks:
      - cqrs-network

  command-service:
    build:
      context: ./command-service
      dockerfile: DockerFile
    container_name: command-service
    restart: always
    depends_on:
      - mysql-command
      - redis
      - rabbitmq
    environment:
      - APP_ENV=local
      - DB_HOST=mysql-command
      - DB_DATABASE=command_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      # - DB_PORT=33062
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
    networks:
      - cqrs-network
    ports:
      - "8001:9000"
    volumes:
      - ./apps/command-service:/var/www/command-service
      - ./apps/command-service/storage:/var/www/command-service/storage
      - ./apps/command-service/vendor:/var/www/command-service/vendor
    # entrypoint: ["./entrypoint.sh"]

  query-service:
    build:
      context: ./query-service
      dockerfile: DockerFile
    container_name: query-service
    restart: always
    depends_on:
      - mysql-query
      - redis
      - rabbitmq
    environment:
      - APP_ENV=local
      - DB_HOST=mysql-query
      - DB_DATABASE=query_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      # - DB_PORT=33061
      - CACHE_DRIVER=redis
    networks:
      - cqrs-network
    ports:
      - "8002:9000"
    volumes:
      - ./apps/query-service:/var/www/query-service
      - ./apps/query-service/storage:/var/www/query-service/storage
      - ./apps/query-service/vendor:/var/www/query-service/vendor
    # entrypoint: ["./entrypoint.sh"]

  mysql-command:
    image: mysql:8.0
    container_name: mysql-command
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: command_db
      # MYSQL_DATABASE: query_db
    ports:
      - "33062:3306"
    networks:
      - cqrs-network
    volumes:
      - mysql_command_data:/var/lib/mysql

  mysql-query:
    image: mysql:8.0
    container_name: mysql-query
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: query_db
    ports:
      - "33061:3306"
    networks:
      - cqrs-network
    volumes:
      - mysql_query_data:/var/lib/mysql


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cqrs-network
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cqrs-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  cqrs-network:
    driver: bridge

volumes:
  mysql_command_data:
  mysql_query_data:
  redis_data:
