FROM php:8.2-fpm

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    netcat-traditional \
    zip \
    unzip \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl gd

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Criar diretório da aplicação
WORKDIR /var/www

# Copiar arquivos da aplicação
COPY . /var/www

# Definir permissões
# RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Instalar dependências do Laravel
# RUN composer install --no-dev --optimize-autoloader

# Garante que o script tenha permissão de execução
# RUN chmod +x ../../apps/query-service/entrypoint.sh

# Define o entrypoint
# ENTRYPOINT ["../../apps/query-service/entrypoint.sh"]

# Expor a porta do PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]